export const QuestionList = {
  naki: {
    id: 'naki',
    title: 'ポン、チーをしていますか？',
    description: 'ポン、チーをしていますか？',
    choices: ['はい', 'いいえ'],
    values: ['yes', 'no'],
  },
  ronTsumo: {
    id: 'ronTsumo',
    title: 'ツモ、ロンどちらで上がりましたか？',
    description: 'ツモ、ロンどちらで上がりましたか？',
    choices: ['ツモ', 'ロン'],
    values: ['tsumo', 'ron'],
  },
  oya: {
    id: 'oya',
    title: '親ですか？',
    description: '親ですか？',
    choices: ['親', '子'],
    values: ['oya', 'ko'],
  },
}

export const disabledKeys = {
  oyaDisabledKey: 'oyaDisabled',
  koDisabledKey: 'koDisabled',
  ronDisabledKey: 'ronDisabled',
  tsumoDisabledKey: 'tsumoDisabled',
  nakiDisabledKey: 'nakiDisabled',
  shuntsuDisabledKey: 'shuntsuDisabled',
  toitsuDisabledKey: 'toitsuDisabled',
  kotsuDisabledKey: 'kotsuDisabled',
  kantsuDisabledKey: 'kantsuDisabled',
  jihaiDisabledKey: 'jihaiDisabled',
}

export const yakuNumberSections = [
  {
    yakuNumber: '1',
    alias: '1翻役',
  },
  {
    yakuNumber: '2',
    alias: '2翻役',
  },
  {
    yakuNumber: '3',
    alias: '3翻役',
  },
  {
    yakuNumber: '6',
    alias: '6翻役',
  },
  {
    yakuNumber: '13',
    alias: '役満',
  },
  {
    yakuNumber: '26',
    alias: 'ダブル役満',
  },
]

export const yakuNumberGroup = [
  [1],
  [2],
  [3],
  [4, 5],
  [6, 7],
  [8, 9, 10],
  [11, 12],
  [13],
  [26],
]

export const yakuEnglishNameGroup = [
  'iHan',
  'ryanHan',
  'sanHan',
  'mangan',
  'haneman',
  'baiman',
  'sanbaiman',
  'yakuman',
  'doubleYakuman',
]

export const score = {
  iHan: {
    name: '1翻',
    payment: {
      parentAgari: {
        score: '1500',
        ronAgari: '1500',
        tsumoAgari: {
          childrenPayment: '500',
        },
      },
      childrenAgari: {
        score: '1000',
        ronAgari: '1000',
        tsumoAgari: {
          parentPayment: '500',
          childrenPayment: '300',
        },
      },
    },
  },
  ryanHan: {
    name: '2翻',
    payment: {
      parentAgari: {
        score: '3000',
        ronAgari: '3000',
        tsumoAgari: {
          childrenPayment: '1000',
        },
      },
      childrenAgari: {
        score: '2000',
        ronAgari: '2000',
        tsumoAgari: {
          parentPayment: '1000',
          childrenPayment: '500',
        },
      },
    },
  },
  sanHan: {
    name: '3翻',
    payment: {
      parentAgari: {
        score: '6000',
        ronAgari: '6000',
        tsumoAgari: {
          childrenPayment: '2000',
        },
      },
      childrenAgari: {
        score: '4000',
        ronAgari: '4000',
        tsumoAgari: {
          parentPayment: '2000',
          childrenPayment: '1000',
        },
      },
    },
  },
  mangan: {
    name: '満貫',
    payment: {
      parentAgari: {
        score: '12000',
        ronAgari: '12000',
        tsumoAgari: {
          childrenPayment: '4000',
        },
      },
      childrenAgari: {
        score: '8000',
        ronAgari: '8000',
        tsumoAgari: {
          parentPayment: '4000',
          childrenPayment: '2000',
        },
      },
    },
  },
  haneman: {
    name: '跳満',
    payment: {
      parentAgari: {
        score: '18000',
        ronAgari: '18000',
        tsumoAgari: {
          childrenPayment: '6000',
        },
      },
      childrenAgari: {
        score: '12000',
        ronAgari: '12000',
        tsumoAgari: {
          parentPayment: '6000',
          childrenPayment: '3000',
        },
      },
    },
  },
  baiman: {
    name: '倍満',
    payment: {
      parentAgari: {
        score: '24000',
        ronAgari: '24000',
        tsumoAgari: {
          childrenPayment: '8000',
        },
      },
      childrenAgari: {
        score: '16000',
        ronAgari: '16000',
        tsumoAgari: {
          parentPayment: '8000',
          childrenPayment: '4000',
        },
      },
    },
  },
  sanbaiman: {
    name: '三倍満',
    payment: {
      parentAgari: {
        score: '36000',
        ronAgari: '36000',
        tsumoAgari: {
          childrenPayment: '12000',
        },
      },
      childrenAgari: {
        score: '24000',
        ronAgari: '24000',
        tsumoAgari: {
          parentPayment: '12000',
          childrenPayment: '6000',
        },
      },
    },
  },
  yakuman: {
    name: '役満',
    payment: {
      parentAgari: {
        score: '48000',
        ronAgari: '48000',
        tsumoAgari: {
          childrenPayment: '16000',
        },
      },
      childrenAgari: {
        score: '32000',
        ronAgari: '32000',
        tsumoAgari: {
          parentPayment: '16000',
          childrenPayment: '8000',
        },
      },
    },
  },
  doubleYakuman: {
    name: 'ダブル役満',
    payment: {
      parentAgari: {
        score: '96000',
        ronAgari: '96000',
        tsumoAgari: {
          childrenPayment: '32000',
        },
      },
      childrenAgari: {
        score: '64000',
        ronAgari: '64000',
        tsumoAgari: {
          parentPayment: '32000',
          childrenPayment: '16000',
        },
      },
    },
  },
}

export const errorText = {
  IsOver: `13翻以下で選択してください`,
}

export const yakus = [
  {
    id: 'reach',
    content: '立直',
    yakuNumber: '1',
    explanationImage: 'aaa',
    explanationText: `テンパイ時に「リーチ」と宣言し、場に1,000点棒を出すことで成立`,
    annotationTexts: [],
  },
  {
    id: 'menzenchintsumo',
    content: '門前自摸（ツモ）',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `ポン・チーなどをせずに、ツモによって上がることで成立`,
    annotationTexts: [],
  },
  {
    id: 'ippatsu',
    content: '一発',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `リーチ宣言後の1巡目以内に、上がることで成立`,
    annotationTexts: [`1巡目以内にポン・チー・明槓がされた場合不成立`],
  },
  {
    id: 'haku',
    content: '白',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `白で刻子や槓子を揃えると成立`,
    annotationTexts: [],
  },
  {
    id: 'hatsu',
    content: '發',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `發で刻子や槓子を揃えると成立`,
    annotationTexts: [],
  },
  {
    id: 'chun',
    content: '中',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `中で刻子や槓子を揃えると成立`,
    annotationTexts: [],
  },
  {
    id: 'jikazehai',
    content: '自風牌',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `自風牌で刻子や槓子を揃えると成立`,
    annotationTexts: [],
  },
  {
    id: 'bakazehai',
    content: '場風牌',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `場風牌で刻子や槓子を揃えると成立`,
    annotationTexts: [],
  },
  {
    id: 'tanyao',
    content: '断么九',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `2~8の牌のみで手牌を揃えると成立`,
    annotationTexts: [],
  },
  {
    id: 'pinfu',
    content: '平和',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `4つのメンツをすべて順子で揃えると成立`,
    annotationTexts: [
      `頭は三元牌、場風牌、自風牌以外で揃える`,
      `両面待ちの場合のみ成立`,
    ],
  },
  {
    id: 'ipeko',
    content: '一盃口',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `一盃口の解説`,
    annotationTexts: [],
  },
  {
    id: 'haitei',
    content: '海底撈月',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `海底撈月の解説`,
    annotationTexts: [],
  },
  {
    id: 'hotei',
    content: '河底撈魚',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `河底撈魚の解説`,
    annotationTexts: [],
  },
  {
    id: 'rinshankaiho',
    content: '嶺上開花',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `嶺上開花の解説`,
    annotationTexts: [],
  },
  {
    id: 'chankan',
    content: '槍槓',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `槍槓の解説`,
    annotationTexts: [],
  },
  {
    id: 'dora',
    content: 'ドラ',
    yakuNumber: '1',
    explanationImage: '',
    explanationText: `ドラの解説`,
    annotationTexts: [],
  },
  {
    id: 'doubleReach',
    content: 'ダブル立直',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `ダブル立直の解説`,
    annotationTexts: [],
  },
  {
    id: 'sanshokuDoujun',
    content: '三色同順',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `三色同順の解説`,
    annotationTexts: [],
  },
  {
    id: 'sanshokuDoko',
    content: '三色同刻',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `三色同刻の解説`,
    annotationTexts: [],
  },
  {
    id: 'toitoiho',
    content: '対々和',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `対々和の解説`,
    annotationTexts: [],
  },
  {
    id: 'chitoitsu',
    content: '七対子',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `七対子の解説`,
    annotationTexts: [],
  },
  {
    id: 'ikkitsukan',
    content: '一気通貫',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `一気通貫の解説`,
    annotationTexts: [],
  },
  {
    id: 'chanta',
    content: '混全帯幺九',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `混全帯幺九の解説`,
    annotationTexts: [],
  },
  {
    id: 'sananko',
    content: '三暗刻',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `三暗刻の解説`,
    annotationTexts: [],
  },
  {
    id: 'shosangen',
    content: '小三元',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `小三元の解説`,
    annotationTexts: [],
  },
  {
    id: 'honroto',
    content: '混老頭',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `混老頭の解説`,
    annotationTexts: [],
  },
  {
    id: 'sankantsu',
    content: '三槓子',
    yakuNumber: '2',
    explanationImage: '',
    explanationText: `三槓子の解説`,
    annotationTexts: [],
  },
  {
    id: 'honitsu',
    content: '混一色',
    yakuNumber: '3',
    explanationImage: '',
    explanationText: `混一色の解説`,
    annotationTexts: [],
  },
  {
    id: 'ryanpeko',
    content: '二盃口',
    yakuNumber: '3',
    explanationImage: '',
    explanationText: `二盃口の解説`,
    annotationTexts: [],
  },
  {
    id: 'junchan',
    content: '純全帯公九',
    yakuNumber: '3',
    explanationImage: '',
    explanationText: `純全帯公九の解説`,
    annotationTexts: [],
  },
  {
    id: 'chinitsu',
    content: '清一色',
    yakuNumber: '6',
    explanationImage: '',
    explanationText: `清一色の解説`,
    annotationTexts: [],
  },
  {
    id: 'suanko',
    content: '四暗刻',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `四暗刻の解説`,
    annotationTexts: [],
  },
  {
    id: 'daisangen',
    content: '大三元',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `大三元の解説`,
    annotationTexts: [],
  },
  {
    id: 'kokushimuso',
    content: '国士無双',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `国士無双の解説`,
    annotationTexts: [],
  },
  {
    id: 'shosushi',
    content: '小四喜',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `小四喜の解説`,
    annotationTexts: [],
  },
  {
    id: 'daisushi',
    content: '大四喜',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `大四喜の解説`,
    annotationTexts: [],
  },
  {
    id: 'tsuiso',
    content: '字一色',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `字一色の解説`,
    annotationTexts: [],
  },
  {
    id: 'chinroto',
    content: '清老頭',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `清老頭の解説`,
    annotationTexts: [],
  },
  {
    id: 'ryuiso',
    content: '緑一色',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `緑一色の解説`,
    annotationTexts: [],
  },
  {
    id: 'sukantsu',
    content: '四槓子',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `四槓子の解説`,
    annotationTexts: [],
  },
  {
    id: 'churenpoto',
    content: '九蓮宝燈',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `九蓮宝燈の解説`,
    annotationTexts: [],
  },
  {
    id: 'chiho',
    content: '地和',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `地和の解説`,
    annotationTexts: [],
  },
  {
    id: 'tenho',
    content: '天和',
    yakuNumber: '13',
    explanationImage: '',
    explanationText: `天和の解説`,
    annotationTexts: [],
  },
  {
    id: 'suanko_daisangen',
    content: '四暗刻＋大三元',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '四暗刻＋大三元の解説',
    annotationTexts: [],
  },
  {
    id: 'suanko_tsuiso',
    content: '四暗刻＋字一色',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '四暗刻＋字一色の解説',
    annotationTexts: [],
  },
  {
    id: 'tsuiso_daisangen',
    content: '字一色＋大三元',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '字一色＋大三元の解説',
    annotationTexts: [],
  },
  {
    id: 'tsuiso_shosushi',
    content: '字一色＋小四喜',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '字一色＋小四喜の解説',
    annotationTexts: [],
  },
  {
    id: 'tsuiso_daisushi',
    content: '字一色＋大四喜',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '字一色＋大四喜の解説',
    annotationTexts: [],
  },
  {
    id: 'ryuiso_suanko',
    content: '緑一色＋四暗刻',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '緑一色＋四暗刻の解説',
    annotationTexts: [],
  },
  {
    id: 'ryuiso_sukantsu',
    content: '緑一色＋四槓子',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '緑一色＋四槓子の解説',
    annotationTexts: [],
  },
  {
    id: 'daisushi_sukantsu',
    content: '大四喜＋四槓子',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '大四喜＋四槓子の解説',
    annotationTexts: [],
  },
  {
    id: 'chinroto_suanko',
    content: '清老頭＋四暗刻',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '清老頭＋四暗刻の解説',
    annotationTexts: [],
  },
  {
    id: 'chinroto_sukantsu',
    content: '清老頭＋四槓子',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '清老頭＋四槓子の解説',
    annotationTexts: [],
  },
  {
    id: 'sukantsu_suanko',
    content: '四槓子＋四暗刻',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '四槓子＋四暗刻の解説',
    annotationTexts: [],
  },
  {
    id: 'sukantsu_tsuiso',
    content: '四槓子＋字一色',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '四槓子＋字一色の解説',
    annotationTexts: [],
  },
  {
    id: 'suankoTanki',
    content: '四暗刻単騎',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '四暗刻単騎の解説',
    annotationTexts: [],
  },
  {
    id: 'kokushimusoJusanmenmachi',
    content: '国士無双13面待ち',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '国士無双13面待ちの解説',
    annotationTexts: [],
  },
  {
    id: 'junseiChurenpoto',
    content: '純正九蓮宝燈',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '純正九蓮宝燈の解説',
    annotationTexts: [],
  },
  {
    id: 'hatsunashiRyuiso',
    content: '發なし緑一色',
    yakuNumber: '26',
    explanationImage: '',
    explanationText: '發なし緑一色の解説',
    annotationTexts: [],
  },
]
