import { atom } from 'recoil'
import { QuestionList } from '../../constants/constants'

export const nakiStatus = atom({
  key: 'nakiStatus',
  default: {
    id: 'naki',
    status: false,
    selectedValue: QuestionList.naki.values[1],
    choices: QuestionList.naki.choices,
    values: QuestionList.naki.values,
  },
})

export const ronTsumoStatus = atom({
  key: 'ronTsumoStatus',
  default: {
    id: 'ronTsumo',
    status: false,
    selectedValue: QuestionList.ronTsumo.values[1],
    choices: QuestionList.ronTsumo.choices,
    values: QuestionList.ronTsumo.values,
  },
})

export const oyaStatus = atom({
  key: 'oyaStatus',
  default: {
    id: 'oya',
    status: false,
    selectedValue: QuestionList.oya.values[1],
    choices: QuestionList.oya.choices,
    values: QuestionList.oya.values,
  },
})

export const dora = atom({
  key: 'dora',
  default: [
    {
      id: 'dora',
      content: 'ドラ',
      yakuNumber: '1',
      value: 0,
    },
  ],
})

const setYakuType = (arg) => {
  const yakuType = []
  arg.disabledValues.shuntsuDisabled || yakuType.push('shuntsu')
  arg.disabledValues.toitsuDisabled || yakuType.push('toitsu')
  arg.disabledValues.kotsuDisabled || yakuType.push('kotsu')
  arg.disabledValues.kantsuDisabled || yakuType.push('kantsu')
  arg.disabledValues.jihaiDisabled || yakuType.push('jihai')
  return yakuType.length < 5 ? yakuType : ['normal']
}

export const yakuList = atom({
  key: 'yakuList',
  default: [
    {
      id: 'reach',
      content: '立直',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'menzenchintsumo',
      content: '門前自摸（ツモ）',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: true,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'ippatsu',
      content: '一発',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'haku',
      content: '白',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'hatsu',
      content: '發',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'chun',
      content: '中',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'jikazehai',
      content: '自風牌',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'bakazehai',
      content: '場風牌',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'tanyao',
      content: '断么九',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: true,
        kantsuDisabled: true,
        jihaiDisabled: true,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'pinfu',
      content: '平和',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: true,
        kantsuDisabled: true,
        jihaiDisabled: true,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'ipeko',
      content: '一盃口',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'haitei',
      content: '海底撈月',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: true,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'hotei',
      content: '河底撈魚',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: true,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'rinshankaiho',
      content: '嶺上開花',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: true,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'chankan',
      content: '槍槓',
      yakuNumber: '1',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: true,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'dora',
      content: 'ドラ',
      yakuNumber: '1',
      value: 0,
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'doubleReach',
      content: 'ダブル立直',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: false,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'sanshokuDoujun',
      content: '三色同順',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '1',
      IsDisabled: false,
    },
    {
      id: 'sanshokuDoko',
      content: '三色同刻',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'toitoiho',
      content: '対々和',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'chitoitsu',
      content: '七対子',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: false,
        kotsuDisabled: true,
        kantsuDisabled: true,
        jihaiDisabled: true,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'ikkitsukan',
      content: '一気通貫',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '1',
      IsDisabled: false,
    },
    {
      id: 'chanta',
      content: '混全帯幺九',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '1',
      IsDisabled: false,
    },
    {
      id: 'sananko',
      content: '三暗刻',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'shosangen',
      content: '小三元',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'honroto',
      content: '混老頭',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'sankantsu',
      content: '三槓子',
      yakuNumber: '2',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'honitsu',
      content: '混一色',
      yakuNumber: '3',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '2',
      IsDisabled: false,
    },
    {
      id: 'ryanpeko',
      content: '二盃口',
      yakuNumber: '3',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: true,
        kantsuDisabled: true,
        jihaiDisabled: true,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'junchan',
      content: '純全帯公九',
      yakuNumber: '3',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: true,
      },
      kuisagari: '2',
      IsDisabled: false,
    },
    {
      id: 'chinitsu',
      content: '清一色',
      yakuNumber: '6',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: true,
      },
      kuisagari: '5',
      IsDisabled: false,
    },
    {
      id: 'suanko',
      content: '四暗刻',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: true,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'daisangen',
      content: '大三元',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'kokushimuso',
      content: '国士無双',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: true,
        kantsuDisabled: true,
        jihaiDisabled: true,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'shosushi',
      content: '小四喜',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'daisushi',
      content: '大四喜',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'tsuiso',
      content: '字一色',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'chinroto',
      content: '清老頭',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'ryuiso',
      content: '緑一色',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'sukantsu',
      content: '四槓子',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: true,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'churenpoto',
      content: '九蓮宝燈',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: true,
        toitsuDisabled: true,
        kotsuDisabled: true,
        kantsuDisabled: true,
        jihaiDisabled: true,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'chiho',
      content: '地和',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: true,
        koDisabled: false,
        ronDisabled: true,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'tenho',
      content: '天和',
      yakuNumber: '13',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: true,
        ronDisabled: true,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'suanko_daisangen',
      content: '四暗刻＋大三元',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'suanko_tsuiso',
      content: '四暗刻＋字一色',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'tsuiso_daisangen',
      content: '字一色＋大三元',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'tsuiso_shosushi',
      content: '字一色＋小四喜',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'tsuiso_daisushi',
      content: '字一色＋大四喜',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'ryuiso_suanko',
      content: '緑一色＋四暗刻',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'ryuiso_sukantsu',
      content: '緑一色＋四槓子',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'daisushi_sukantsu',
      content: '大四喜＋四槓子',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'chinroto_suanko',
      content: '清老頭＋四暗刻',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'chinroto_sukantsu',
      content: '清老頭＋四槓子',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'sukantsu_suanko',
      content: '四槓子＋四暗刻',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'sukantsu_tsuiso',
      content: '四槓子＋字一色',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'suankoTanki',
      content: '四暗刻単騎',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'kokushimusoJusanmenmachi',
      content: '国士無双13面待ち',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'junseiChurenpoto',
      content: '純正九蓮宝燈',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: true,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
    {
      id: 'hatsunashiRyuiso',
      content: '發なし緑一色',
      yakuNumber: '26',
      IsChecked: false,
      yakuType: function () {
        return setYakuType(this)
      },
      disabledValues: {
        nakiDisabled: false,
        oyaDisabled: false,
        koDisabled: false,
        ronDisabled: false,
        tsumoDisabled: false,
        shuntsuDisabled: false,
        toitsuDisabled: true,
        kotsuDisabled: false,
        kantsuDisabled: false,
        jihaiDisabled: false,
      },
      kuisagari: '0',
      IsDisabled: false,
    },
  ],
})
