import { atom } from 'recoil'

export const nakiStatus = atom({
  key: 'nakiStatus',
  default: {
    id: 'naki',
    status: false,
  },
})

export const oyaStatus = atom({
  key: 'oyaStatus',
  default: {
    id: 'oya',
    status: false,
  },
})

export const dora = atom({
  key: 'dora',
  default: [
    {
      id: 'dora',
      content: 'ドラ',
      yakuNumber: '1',
      value: 0,
    },
  ],
})

export const yakuList = atom({
  key: 'yakuList',
  default: [
    {
      id: 'dora',
      content: 'ドラ',
      yakuNumber: '1',
      value: 0,
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'reach',
      content: '立直',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'ippatsu',
      content: '一発',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'menzenchintsumo',
      content: '門前自摸',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'haku',
      content: '白',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'kotsuOnly',
    },
    {
      id: 'hatsu',
      content: '發',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'kotsuOnly',
    },
    {
      id: 'chun',
      content: '中',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'kotsuOnly',
    },
    {
      id: 'jikazehai',
      content: '自風牌',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'kotsuOnly',
    },
    {
      id: 'bakazehai',
      content: '場風牌',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'kotsuOnly',
    },
    {
      id: 'tanyao',
      content: '断么九',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'juntsuOnly',
    },
    {
      id: 'pinfu',
      content: '平和',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'juntsuOnly',
    },
    {
      id: 'ipeko',
      content: '一盃口',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'chankan',
      content: '槍槓',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'rinshankaiho',
      content: '嶺上開花',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'haitei',
      content: '海底撈月',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'hotei',
      content: '河底撈魚',
      yakuNumber: '1',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
      yakuType: 'all',
    },
    {
      id: 'doubleReach',
      content: 'ダブル立直',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'sanshokuDoujun',
      content: '三色同順',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '1',
    },
    {
      id: 'sanshokuDoko',
      content: '三色同刻',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'sananko',
      content: '三暗刻',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'ikkitsukan',
      content: '一気通貫',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '1',
    },
    {
      id: 'chitoitsu',
      content: '七対子',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'toitoiho',
      content: '対々和',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'chanta',
      content: '混全帯幺九',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '1',
    },
    {
      id: 'sankantsu',
      content: '三槓子',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'shosangen',
      content: '小三元',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'honroto',
      content: '混老頭',
      yakuNumber: '2',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'ryanpeko',
      content: '二盃口',
      yakuNumber: '3',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'junchan',
      content: '純全帯公九',
      yakuNumber: '3',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '2',
    },
    {
      id: 'honitsu',
      content: '混一色',
      yakuNumber: '3',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '2',
    },
    {
      id: 'chinitsu',
      content: '清一色',
      yakuNumber: '6',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: true,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '5',
    },
    {
      id: 'suanko',
      content: '四暗刻',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'daisangen',
      content: '大三元',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'kokushimuso',
      content: '国士無双',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'ryuiso',
      content: '緑一色',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'tsuiso',
      content: '字一色',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'chinroto',
      content: '清老頭',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'sukantsu',
      content: '四槓子',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'shosushi',
      content: '小四喜',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'daisushi',
      content: '大四喜',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: false,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'churenpoto',
      content: '九蓮宝燈',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'chiho',
      content: '地和',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: true,
      oyaOnly: false,
      kuisagari: '0',
    },
    {
      id: 'tenho',
      content: '天和',
      yakuNumber: '13',
      IsChecked: false,
      IsDisabled: false,
      normalYaku: false,
      menzenOnly: true,
      oyaOnly: true,
      kuisagari: '0',
    },
  ],
})
